// To use this file, REST Client must be installed in VSCode: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@PORT = {{$dotenv PORT}}
@API = http://localhost:{{PORT}}


### GET /v1/location  -> Get city from client IP address
GET {{API}}/v1/location

